//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace project
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cityEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cityEntities2 object using the connection string found in the 'cityEntities2' section of the application configuration file.
        /// </summary>
        public cityEntities2() : base("name=cityEntities2", "cityEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cityEntities2 object.
        /// </summary>
        public cityEntities2(string connectionString) : base(connectionString, "cityEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cityEntities2 object.
        /// </summary>
        public cityEntities2(EntityConnection connection) : base(connection, "cityEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<adminn> adminns
        {
            get
            {
                if ((_adminns == null))
                {
                    _adminns = base.CreateObjectSet<adminn>("adminns");
                }
                return _adminns;
            }
        }
        private ObjectSet<adminn> _adminns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userr> userrs
        {
            get
            {
                if ((_userrs == null))
                {
                    _userrs = base.CreateObjectSet<userr>("userrs");
                }
                return _userrs;
            }
        }
        private ObjectSet<userr> _userrs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the adminns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadminns(adminn adminn)
        {
            base.AddObject("adminns", adminn);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userrs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserrs(userr userr)
        {
            base.AddObject("userrs", userr);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cityModel11", Name="adminn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adminn : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new adminn object.
        /// </summary>
        /// <param name="admin_id">Initial value of the admin_id property.</param>
        public static adminn Createadminn(global::System.Int32 admin_id)
        {
            adminn adminn = new adminn();
            adminn.admin_id = admin_id;
            return adminn;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 admin_id
        {
            get
            {
                return _admin_id;
            }
            set
            {
                if (_admin_id != value)
                {
                    Onadmin_idChanging(value);
                    ReportPropertyChanging("admin_id");
                    _admin_id = StructuralObject.SetValidValue(value, "admin_id");
                    ReportPropertyChanged("admin_id");
                    Onadmin_idChanged();
                }
            }
        }
        private global::System.Int32 _admin_id;
        partial void Onadmin_idChanging(global::System.Int32 value);
        partial void Onadmin_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String admin_name
        {
            get
            {
                return _admin_name;
            }
            set
            {
                Onadmin_nameChanging(value);
                ReportPropertyChanging("admin_name");
                _admin_name = StructuralObject.SetValidValue(value, true, "admin_name");
                ReportPropertyChanged("admin_name");
                Onadmin_nameChanged();
            }
        }
        private global::System.String _admin_name;
        partial void Onadmin_nameChanging(global::System.String value);
        partial void Onadmin_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String admin_pass
        {
            get
            {
                return _admin_pass;
            }
            set
            {
                Onadmin_passChanging(value);
                ReportPropertyChanging("admin_pass");
                _admin_pass = StructuralObject.SetValidValue(value, true, "admin_pass");
                ReportPropertyChanged("admin_pass");
                Onadmin_passChanged();
            }
        }
        private global::System.String _admin_pass;
        partial void Onadmin_passChanging(global::System.String value);
        partial void Onadmin_passChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cityModel11", Name="userr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userr object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static userr Createuserr(global::System.Int32 user_id)
        {
            userr userr = new userr();
            userr.user_id = user_id;
            return userr;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, "user_id");
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Passwordd
        {
            get
            {
                return _Passwordd;
            }
            set
            {
                OnPassworddChanging(value);
                ReportPropertyChanging("Passwordd");
                _Passwordd = StructuralObject.SetValidValue(value, true, "Passwordd");
                ReportPropertyChanged("Passwordd");
                OnPassworddChanged();
            }
        }
        private global::System.String _Passwordd;
        partial void OnPassworddChanging(global::System.String value);
        partial void OnPassworddChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, "Age");
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone_number
        {
            get
            {
                return _Phone_number;
            }
            set
            {
                OnPhone_numberChanging(value);
                ReportPropertyChanging("Phone_number");
                _Phone_number = StructuralObject.SetValidValue(value, true, "Phone_number");
                ReportPropertyChanged("Phone_number");
                OnPhone_numberChanged();
            }
        }
        private global::System.String _Phone_number;
        partial void OnPhone_numberChanging(global::System.String value);
        partial void OnPhone_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion

    }

    #endregion

}
